spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  liquibase:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
            redirect-uri: "https://000a2143f492.ngrok.io/api/oauth2/callback/google"
            target-uri: "http://localhost:4200/authentication/oauth2/callback"
            scope:
              - email
server:
  forward-headers-strategy: framework
  security:
    authentication:
      jwt:
        base64-secret: ${JWT_AUTH_BASE64_SECRET}
        token-expires-in-seconds: 86400
        refresh-token-expires-in-seconds: 86400
auditing:
  anonymous-principal: system2